# Generated by Django 4.0.7 on 2023-01-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('stockcode', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('linkcode', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('stocktype', models.CharField(default='None', max_length=200, null=True)),
                ('unit', models.CharField(default='None', max_length=200, null=True)),
                ('description', models.CharField(default='None', max_length=200, null=True)),
                ('barcode', models.CharField(default='None', max_length=200, null=True)),
                ('packsize', models.CharField(default='None', max_length=200, null=True)),
                ('onhand', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('avgcostexcl', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('lastcostexcl', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('excl', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('incl', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('defaultgp', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('gp', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('vat', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SaveMore Stock',
            },
        ),
    ]
