# Generated by Django 4.0.7 on 2023-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
