# Generated by Django 4.0.7 on 2023-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_auto_increment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
