# Generated by Django 4.0.7 on 2023-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adminstatus',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='excl',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
