# Generated by Django 4.0.7 on 2023-01-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_adminstatus_alter_myorders_excl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='incl',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
