# Generated by Django 4.0.7 on 2023-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_myorders_grossamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
