# Generated by Django 4.0.7 on 2023-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_myorders_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorders',
            old_name='total',
            new_name='excltotal',
        ),
        migrations.AddField(
            model_name='myorders',
            name='incltotal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
