# Generated by Django 4.0.7 on 2023-02-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'ORDER NUMBERS'},
        ),
    ]
