# Generated by Django 4.0.7 on 2023-03-24 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notenum',
            new_name='bookno',
        ),
        migrations.RenameField(
            model_name='papers',
            old_name='pnumber',
            new_name='bookno',
        ),
        migrations.RenameField(
            model_name='sts',
            old_name='recieptno',
            new_name='bookno',
        ),
        migrations.RenameField(
            model_name='swipes',
            old_name='swipsid',
            new_name='swipno',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='description',
        ),
        migrations.RemoveField(
            model_name='qadadic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='swipes',
            name='description',
        ),
        migrations.CreateModel(
            name='Kazang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookno', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'KAZANG',
            },
        ),
    ]
