# Generated by Django 4.0.7 on 2023-03-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0003_qadadic_cashierorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadadic',
            name='cashierorderid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
