# Generated by Django 4.0.7 on 2023-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0004_alter_qadadic_cashierorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierorders',
            name='adminstatus',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
