# Generated by Django 4.0.7 on 2023-03-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0005_alter_cashierorders_adminstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashierorders',
            old_name='cashid',
            new_name='cashierorid',
        ),
    ]
