# Generated by Django 4.0.7 on 2023-03-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0006_rename_cashid_cashierorders_cashierorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierorders',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
