# Generated by Django 4.0.7 on 2023-03-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0007_cashierorders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazang',
            name='cashierorid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='cashierorid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='papers',
            name='cashierorid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sts',
            name='cashierorid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='swipes',
            name='cashierorid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
