# Generated by Django 4.0.7 on 2023-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0008_kazang_cashierorid_notes_cashierorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierorders',
            name='actualamount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
