# Generated by Django 4.0.7 on 2023-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0009_cashierorders_actualamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierorders',
            name='comment',
            field=models.TextField(blank=True, default='Non', null=True),
        ),
    ]
