# Generated by Django 4.0.7 on 2023-03-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0011_alter_cashierorders_adminstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kazang',
            name='bookno',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='bookno',
        ),
        migrations.RemoveField(
            model_name='swipes',
            name='swipno',
        ),
    ]
