# Generated by Django 4.0.7 on 2023-04-05 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashiers', '0018_alter_kazang_created_at_alter_kazang_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saleslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True)),
                ('grandtotal', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('totalpertype', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SALES LOG',
            },
        ),
    ]
