# Generated by Django 4.0.7 on 2023-04-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0019_saleslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslog',
            name='types',
        ),
    ]
