# Generated by Django 4.0.7 on 2023-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0020_remove_saleslog_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='diff',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='grandtotal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='totalpertype',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
