# Generated by Django 4.0.7 on 2023-04-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0021_saleslog_diff_alter_saleslog_grandtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleslog',
            old_name='customer',
            new_name='cashier',
        ),
    ]
