# Generated by Django 4.0.7 on 2023-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0027_acc_done_kazang_done_notes_done_papers_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='precoin',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
