# Generated by Django 4.0.7 on 2023-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0028_saleslog_precoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='sales',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
