# Generated by Django 4.0.7 on 2023-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
