# Generated by Django 4.0.7 on 2023-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_sales_created_at_alter_sales_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
