# Generated by Django 4.0.7 on 2023-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savemauth', '0003_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
