# Generated by Django 4.0.7 on 2023-03-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savemauth', '0004_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subburb',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
