# Generated by Django 4.0.7 on 2023-03-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savemauth', '0005_user_subburb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subburb',
            new_name='subb',
        ),
    ]
