# Generated by Django 4.0.7 on 2023-07-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savemauth', '0007_user_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
